version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "composer create-project --prefer-dist laravel/laravel project ^8.0 &&
            cd project &&
            php artisan serve --host=0.0.0.0 --port=8000"
